# .github/workflows/release.yml
name: Firmware Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🔧 Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.31.2'
          install-binaryen: 'false'
      - name: 👷 Build
        run: tinygo build -size full -o "norn-firmware_pico_${{ github.ref_name }}.uf2" -target=pico -ldflags="-X 'main.Version=${{ github.ref_name }}'" ./...
      - name: 📚 Changelog
        run: |
          go install github.com/goreleaser/chglog/cmd/chglog@latest
          chglog init
          chglog format --template release > ${{ github.workspace }}-CHANGELOG.txt
      - name: 🔒 Generate checksums
        run: |
          sudo apt-get update
          sudo apt-get install coreutils
          sha256sum firmware_pico.uf2 > checksums.txt
      - name: 🎉 Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          repository: nornforge/firmware
          token: ${{ secrets.GH_PAT }}
          files: |
            norn-firmware_pico_${{ github.ref_name }}.uf2
            checksums.txt
